export const PRODUCTS = [
  {
    id: "1",
    name: "Concealed Door Hinges (Soft Close)",
    category: "Door Hardware",
    price: 1850,
    originalPrice: 2400,
    unit: "Set of 10",
    rating: 4.8,
    reviews: 214,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400"],
    description: "Premium soft-close concealed hinges for modular kitchen and wardrobe shutters. 170° opening, nickel-plated for corrosion resistance.",
  },
  {
    id: "2",
    name: "Wooden Laminate Flooring",
    category: "Flooring",
    price: 42,
    originalPrice: 55,
    unit: "Per sq. ft.",
    rating: 4.7,
    reviews: 312,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1562663474-6cbb3eaa4d14?w=400"],
    description: "8mm AC4 grade laminate flooring with realistic wood grain finish. Water-resistant, suitable for living rooms and bedrooms.",
  },
  {
    id: "3",
    name: "Mortise Lock Set (SS Finish)",
    category: "Locks & Security",
    price: 2200,
    originalPrice: 2800,
    unit: "Per piece",
    rating: 4.9,
    reviews: 178,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400"],
    description: "Heavy-duty stainless steel mortise lock for main doors. Anti-pick, anti-drill cylinder with 5 keys included.",
  },
  {
    id: "4",
    name: "Modular Kitchen Handles",
    category: "Cabinet Hardware",
    price: 320,
    originalPrice: 420,
    unit: "Pack of 20",
    rating: 4.6,
    reviews: 95,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=400"],
    description: "Sleek brushed gold finish handles for modular kitchen cabinets and wardrobes. 160mm hole-to-hole distance.",
  },
  {
    id: "5",
    name: "Gypsum False Ceiling Board",
    category: "Ceiling & Wall",
    price: 38,
    originalPrice: 48,
    unit: "Per sq. ft.",
    rating: 4.5,
    reviews: 143,
    inStock: false,
    images: ["https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=400"],
    description: "12.5mm moisture-resistant gypsum board for false ceilings and partition walls. Fire-rated, smooth surface.",
  },
  {
    id: "6",
    name: "Vitrified Floor Tiles (60×60cm)",
    category: "Tiles",
    price: 58,
    originalPrice: 72,
    unit: "Per sq. ft.",
    rating: 4.7,
    reviews: 267,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=400"],
    description: "Double-charged vitrified tiles with marble finish. High scratch resistance, suitable for heavy foot traffic areas.",
  },
  {
    id: "7",
    name: "Telescopic Channel Drawer Slides",
    category: "Cabinet Hardware",
    price: 980,
    originalPrice: 1200,
    unit: "Set of 5 pairs",
    rating: 4.8,
    reviews: 89,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=400"],
    description: "Full-extension soft-close drawer slides. 45kg load capacity, smooth ball-bearing mechanism.",
  },
  {
    id: "8",
    name: "UPVC Window Frame",
    category: "Windows & Doors",
    price: 420,
    originalPrice: 520,
    unit: "Per sq. ft.",
    rating: 4.6,
    reviews: 112,
    inStock: true,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400"],
    description: "Multi-chamber UPVC window profile with thermal insulation. Sound-proof, UV stabilized, low maintenance.",
  },
];

export const CATEGORIES = [
  { id: "1", name: "Door Hardware", icon: "🚪" },
  { id: "2", name: "Flooring", icon: "🏠" },
  { id: "3", name: "Locks & Security", icon: "🔐" },
  { id: "4", name: "Cabinet Hardware", icon: "🗄️" },
  { id: "5", name: "Ceiling & Wall", icon: "🧱" },
  { id: "6", name: "Tiles", icon: "⬜" },
  { id: "7", name: "Windows & Doors", icon: "🪟" },
  { id: "8", name: "Electrical Fittings", icon: "💡" },
];

export const PROFESSIONALS = [
  {
    id: "1",
    name: "Ramesh Kumar",
    profession: "Interior Designer",
    contact: "+91 98765 43210",
    experience: "8 years",
    rating: 4.7,
    location: "Hyderabad",
    avatar: "RK",
  },
  {
    id: "2",
    name: "Suresh Patel",
    profession: "Carpenter & Modular Kitchen",
    contact: "+91 87654 32109",
    experience: "12 years",
    rating: 4.9,
    location: "Hyderabad",
    avatar: "SP",
  },
  {
    id: "3",
    name: "Anita Sharma",
    profession: "Civil Contractor",
    contact: "+91 76543 21098",
    experience: "5 years",
    rating: 4.5,
    location: "Secunderabad",
    avatar: "AS",
  },
  {
    id: "4",
    name: "Vijay Reddy",
    profession: "Tile & Flooring Specialist",
    contact: "+91 65432 10987",
    experience: "10 years",
    rating: 4.6,
    location: "Hyderabad",
    avatar: "VR",
  },
  {
    id: "5",
    name: "Mohammed Ali",
    profession: "Electrician",
    contact: "+91 54321 09876",
    experience: "7 years",
    rating: 4.8,
    location: "Hyderabad",
    avatar: "MA",
  },
];
